### ISSUE TITLE
Incorrect day counts for certain date ranges

### ISSUE THREAD

**Issue by ANightCoder-Brian** [codebox/moment-precise-range#10]
Hi Rob - thanks for a really great job on precise ranges!!  Works really well.  Notice two issues, however, with 'end of month' date ranges:

Same results for date ranges which differ by one day: 
 - 10/30/1996 - 10/25/2015 - 18 years, 11 months, 25 days
 - 10/31/1996 - 10/25/2015 - 18 years, 11 months, 25 days

Inconsistent results for date ranges which differ by one day:
 - 02/28/1996 - 10/25/2015 - 19 years, 7 months, 27 days
 - 03/01/1996 - 10/25/2015 = 19 years, 7 months, 24 days

Best.

Brian

**Comment by codebox** [comment]
Thanks for submitting this, I think there will always be some strangeness due to the fact that months have different numbers of days.

I hope the following explains the difficulty:

    2013-01-28 -> 2013-02-28 // '1 month'

Now advance the second date so the interval is 1 day longer:

    2013-01-28 -> 2013-03-01 // ???

Should this be '1 month 1 day' because it's 1 day longer than previous, or '1 month 4 days' because it is 4 days longer than `2013-02-01 -> 2013-03-01`? 

This problem arises whenever the month containing the start date has more days than the last full month of the interval (in your first example October 1996 has 31 days but September 2015 has only 30 days)

I think whatever approach we take there will always be some examples that seem wrong, you can see some test cases that illustrate the 'compromise solution' I came up with [here](https://github.com/codebox/moment-precise-range/blob/master/readable-range-test.js#L86).
